CREATE SCHEMA "TRAVEL";

CREATE COLUMN TABLE "TRAVEL"."Airports" (
    "airportCode" NVARCHAR(3) NOT NULL,
    "airportName" NVARCHAR(100),
    "city" NVARCHAR(100),
    "country" NVARCHAR(100),
    "location" ST_GEOMETRY (4326),
    "altitude" INTEGER,
    "offsetUTC" INTEGER,
    "passengers" INTEGER,
    PRIMARY KEY ("airportCode"))
;

CREATE COLUMN TABLE "TRAVEL"."Routes" ("routeId" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "airlineCode" NVARCHAR(2) NOT NULL,
    "airlineName" NVARCHAR(100),
    "allianceName" NVARCHAR(100),
    "airportCodeOrigin" NVARCHAR(3) NOT NULL,
    "airportCodeDestination" NVARCHAR(3) NOT NULL,
    "distance" INTEGER,
    "duration" INTEGER,
    PRIMARY KEY ("routeId"))
;

INSERT INTO "TRAVEL"."Airports" VALUES ('AMS','Amsterdam Airport Schiphol','Amsterdam','Netherlands',new ST_POINT('POINT(4.76388979 52.30860138)',4326),-11,1,64);
INSERT INTO "TRAVEL"."Airports" VALUES ('ATL','Hartsfield Jackson Atlanta International Airport','Atlanta','United States',new ST_POINT('POINT(-84.42810059 33.63669968)',4326),1026,-5,104);
INSERT INTO "TRAVEL"."Airports" VALUES ('CDG','Charles de Gaulle International Airport','Paris','France',new ST_POINT('POINT(2.549999952 49.01279831)',4326),392,1,66);
INSERT INTO "TRAVEL"."Airports" VALUES ('DFW','Dallas Fort Worth International Airport','Dallas-Fort Worth','United States',new ST_POINT('POINT(-97.03800201 32.89680099)',4326),607,-6,66);
INSERT INTO "TRAVEL"."Airports" VALUES ('DXB','Dubai International Airport','Dubai','United Arab Emirates',new ST_POINT('POINT(55.36439896 25.25279999)',4326),62,4,84);
INSERT INTO "TRAVEL"."Airports" VALUES ('FRA','Frankfurt am Main International Airport','Frankfurt','Germany',new ST_POINT('POINT(8.5705556 50.0333333)',4326),364,1,61);
INSERT INTO "TRAVEL"."Airports" VALUES ('HND','Tokyo Haneda International Airport','Tokyo','Japan',new ST_POINT('POINT(139.779999 35.552299)',4326),35,9,80);
INSERT INTO "TRAVEL"."Airports" VALUES ('JFK','John F Kennedy International Airport','New York','United States',new ST_POINT('POINT(-73.77890015 40.63980103)',4326),13,-5,58);
INSERT INTO "TRAVEL"."Airports" VALUES ('LAX','Los Angeles International Airport','Los Angeles','United States',new ST_POINT('POINT(-118.4079971 33.94250107)',4326),125,-8,81);
INSERT INTO "TRAVEL"."Airports" VALUES ('LHR','London Heathrow Airport','London','United Kingdom',new ST_POINT('POINT(-0.461941 51.4706)',4326),83,0,75);
INSERT INTO "TRAVEL"."Airports" VALUES ('NTE','Nantes Atlantique Airport','Nantes','France',new ST_POINT('POINT(-1.610730052 47.15319824)',4326),90,1,5);
INSERT INTO "TRAVEL"."Airports" VALUES ('ORD','Chicago O Hare International Airport','Chicago','United States',new ST_POINT('POINT(-87.90480042 41.97859955)',4326),672,-6,78);
INSERT INTO "TRAVEL"."Airports" VALUES ('PDX','Portland International Airport','Portland','United States',new ST_POINT('POINT(-122.5979996 45.58869934)',4326),31,-8,17);
INSERT INTO "TRAVEL"."Airports" VALUES ('PVG','Shanghai Pudong International Airport','Shanghai','China',new ST_POINT('POINT(121.8050003 31.14340019)',4326),13,8,66);
INSERT INTO "TRAVEL"."Airports" VALUES ('SFO','San Francisco International Airport','San Francisco','United States',new ST_POINT('POINT(-122.375 37.6189994812011)',4326),13,-8,45);
INSERT INTO "TRAVEL"."Airports" VALUES ('YVR','Vancouver International Airport','Vancouver','Canada',new ST_POINT('POINT(-123.183998108 49.193901062)',4326),14,-8,22);

INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','ATL','CDG',4394,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','ATL',4394,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','DXB',3259,7);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','FRA',280,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','HND',6046,14);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','JFK',3635,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','LAX',5669,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','LHR',216,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','NTE',231,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','ORD',4152,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','PVG',5771,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','CDG','SFO',5583,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','DXB','CDG',3259,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','FRA','CDG',280,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','HND','CDG',6046,14);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','JFK','CDG',3635,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','LAX','CDG',5669,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','LHR','CDG',216,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','NTE','CDG',231,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','ORD','CDG',4152,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','PVG','CDG',5771,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('AF','Air France','SkyTeam','SFO','CDG',5583,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','AMS','ATL',4401,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','AMS','JFK',3643,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','AMS','PDX',5004,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','AMS',4401,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','CDG',4394,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','DFW',731,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','DXB',7599,16);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','FRA',4615,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','JFK',760,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','LAX',1946,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','LHR',4211,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','ORD',606,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','PDX',2172,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ATL','SFO',2139,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','CDG','ATL',4394,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','CDG','JFK',3635,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','CDG','LAX',5669,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','DFW','ATL',731,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','DXB','ATL',7599,16);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','FRA','ATL',4615,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','FRA','JFK',3856,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','HND','LAX',5488,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','AMS',3643,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','ATL',760,3);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','CDG',3635,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','DFW',1391,3);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','FRA',3856,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','LAX',2475,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','LHR',3451,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','ORD',740,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','PDX',2454,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','PVG',7392,15);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','JFK','SFO',2586,7);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','LAX','ATL',1946,4);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','LAX','HND',5488,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','LAX','JFK',2475,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','LHR','ATL',4211,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','LHR','JFK',3451,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ORD','ATL',606,3);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','ORD','CDG',4152,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','PDX','AMS',5004,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','PDX','ATL',2172,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','PDX','JFK',2454,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','PVG','JFK',7392,16);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','PVG','SFO',6150,14);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','SFO','ATL',2139,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','SFO','JFK',2586,6);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('DL','Delta Air Lines','SkyTeam','SFO','PVG',6150,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','ATL',4401,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','DFW',4920,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','DXB',3215,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','JFK',3643,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','LAX',5578,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','LHR',231,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','ORD',4120,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','PVG',5549,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','SFO',5473,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','AMS','YVR',4804,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','ATL','AMS',4401,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','DFW','AMS',4920,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','DXB','AMS',3215,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','JFK','AMS',3643,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','LAX','AMS',5578,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','LHR','AMS',231,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','ORD','AMS',4120,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','PVG','AMS',5549,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','SFO','AMS',5473,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('KL','KLM Royal Dutch Airlines','SkyTeam','YVR','AMS',4804,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','AMS','FRA',228,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','ATL','FRA',4615,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','CDG','FRA',280,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','DFW','FRA',5143,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','DXB','FRA',3012,7);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','AMS',228,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','ATL',4615,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','CDG',280,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','DFW',5143,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','DXB',3012,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','HND',5831,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','JFK',3856,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','LAX',5806,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','LHR',408,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','ORD',4344,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','PVG',5516,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','SFO',5699,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','FRA','YVR',5025,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','HND','FRA',5831,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','JFK','FRA',3856,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','LAX','FRA',5806,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','LHR','FRA',408,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','ORD','FRA',4344,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','PVG','FRA',5516,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','SFO','FRA',5699,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('LH','Lufthansa','Star Alliance','YVR','FRA',5025,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','AMS','ORD',4120,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ATL','SFO',2139,6);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','CDG','ORD',4152,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','CDG','SFO',5583,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','DFW','ORD',802,3);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','DFW','SFO',1464,3);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','FRA','ORD',4344,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','FRA','SFO',5699,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','JFK','LAX',2475,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','JFK','SFO',2586,7);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LAX','JFK',2475,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LAX','LHR',5456,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LAX','ORD',1745,4);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LAX','PVG',6485,15);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LAX','SFO',337,1);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LHR','LAX',5456,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LHR','ORD',3953,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','LHR','SFO',5368,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','AMS',4120,10);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','CDG',4152,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','DFW',802,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','FRA',4344,9);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','LAX',1745,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','LHR',3953,8);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','PDX',1739,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','PVG',7057,15);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','SFO',1846,4);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','ORD','YVR',1764,4);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','PDX','ORD',1739,5);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','PDX','SFO',550,3);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','PVG','LAX',6485,15);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','PVG','ORD',7057,16);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','PVG','SFO',6150,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','ATL',2139,6);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','CDG',5583,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','DFW',1464,4);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','FRA',5699,12);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','JFK',2586,7);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','LAX',337,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','LHR',5368,11);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','ORD',1846,4);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','PDX',550,3);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','PVG',6150,13);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','SFO','YVR',800,2);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','YVR','ORD',1764,4);
INSERT INTO "TRAVEL"."Routes" ("airlineCode","airlineName","allianceName", "airportCodeOrigin","airportCodeDestination","distance","duration") VALUES ('UA','United Airlines','Star Alliance','YVR','SFO',800,3);

---

CREATE GRAPH WORKSPACE "TRAVEL"."Flights"
    EDGE TABLE "TRAVEL"."Routes"
        SOURCE COLUMN "airportCodeOrigin"
        TARGET COLUMN "airportCodeDestination"
        KEY COLUMN "routeId"
    VERTEX TABLE "TRAVEL"."Airports"
        KEY COLUMN "airportCode"
    ;

SELECT * FROM GRAPH_WORKSPACES;
SELECT * FROM GRAPH_WORKSPACE_COLUMNS;

---

CREATE PROCEDURE "TRAVEL"."SP_TripPossible" (
        IN airportCodeOrigin NVARCHAR(3),
        IN airportCodeDestination NVARCHAR(3),
        OUT isPossible BOOLEAN
    )
    LANGUAGE GRAPH READS SQL DATA AS
    BEGIN
        Graph g = Graph("TRAVEL", "Flights");
        Vertex sourceVertex = Vertex(:g, :airportCodeOrigin);
        Vertex targetVertex = Vertex(:g, :airportCodeDestination);
        isPossible = IS_REACHABLE(:g, :sourceVertex, :targetVertex);
    END
    ;

CALL "TRAVEL"."SP_TripPossible"('NTE','PDX',?);

---

CREATE TYPE "TRAVEL"."TT_TripRouting" AS TABLE (
    "segment" BIGINT,
    "airportCodeOrigin" NVARCHAR(3),
    "airportCodeDestination" NVARCHAR(3),
    "airlineName" NVARCHAR(100),
    "distance" INTEGER,
    "duration" INTEGER
    );

CREATE PROCEDURE "TRAVEL"."SP_TripRouting" (
        IN airportCodeOrigin NVARCHAR(3),
        IN airportCodeDestination NVARCHAR(3),
        OUT totalSegments BIGINT,
        OUT totalDistance INTEGER,
        OUT totalDuration INTEGER,
        OUT routing "TRAVEL"."TT_TripRouting"
    )
    LANGUAGE GRAPH READS SQL DATA AS
    BEGIN
        Graph g = Graph("TRAVEL", "Flights");
        Vertex sourceVertex = Vertex(:g, :airportCodeOrigin);
        Vertex targetVertex = Vertex(:g, :airportCodeDestination);
        WeightedPath<BigInt> p = SHORTEST_PATH(:g, :sourceVertex, :targetVertex);
        totalSegments = Length(:p);
        totalDistance = 0;
        totalDuration = 0;
        FOREACH e IN Edges(:p) {
            totalDistance = :totalDistance + :e."distance";
            totalDuration = :totalDuration + :e."duration";
        }
        routing = SELECT :segment, :e."airportCodeOrigin",  :e."airportCodeDestination", :e."airlineName", :e."distance", :e."duration" FOREACH e in Edges(:p) WITH ORDINALITY AS segment;
    END
    ;

CALL "TRAVEL"."SP_TripRouting"('NTE','PDX',?,?,?,?);

---

CREATE PROCEDURE "TRAVEL"."SP_WeightedTripRouting" (
        IN weight VARCHAR(10),
        IN airportCodeOrigin NVARCHAR(3),
        IN airportCodeDestination NVARCHAR(3),
        OUT totalSegments BIGINT,
        OUT totalDistance INTEGER,
        OUT totalDuration INTEGER,
        OUT routing "TRAVEL"."TT_TripRouting"
    )
    LANGUAGE GRAPH READS SQL DATA AS
    BEGIN
        Graph g = Graph("TRAVEL", "Flights");
        Vertex sourceVertex = Vertex(:g, :airportCodeOrigin);
        Vertex targetVertex = Vertex(:g, :airportCodeDestination);
        totalDistance = 0;
        totalDuration = 0;
        IF (:weight == 'distance') {
            WeightedPath<Int> p = SHORTEST_PATH(:g, :sourceVertex, :targetVertex, (Edge e) => Int {return :e."distance";});
            totalSegments = Length(:p);
            totalDistance = Weight(:p);
            FOREACH e IN Edges(:p) {
                totalDuration = :totalDuration + :e."duration";
            }	
            routing = SELECT :segment, :e."airportCodeOrigin",  :e."airportCodeDestination", :e."airlineName", :e."distance", :e."duration" FOREACH e in Edges(:p) WITH ORDINALITY AS segment;
        } ELSE {
            IF (:weight == 'duration') {
                WeightedPath<Int> p = SHORTEST_PATH(:g, :sourceVertex, :targetVertex, (Edge e) => Int {return :e."duration";});
                totalSegments = Length(:p);
                totalDuration = Weight(:p);
                FOREACH e IN Edges(:p) {
                    totalDistance = :totalDistance + :e."distance";
                }
                routing = SELECT :segment, :e."airportCodeOrigin",  :e."airportCodeDestination", :e."airlineName", :e."distance", :e."duration" FOREACH e in Edges(:p) WITH ORDINALITY AS segment;
            } ELSE {
                WeightedPath<BigInt> p = SHORTEST_PATH(:g, :sourceVertex, :targetVertex);
                totalSegments = Length(:p);
                FOREACH e IN Edges(:p) {
                    totalDistance = :totalDistance + :e."distance";
                    totalDuration = :totalDuration + :e."duration";
                }
                routing = SELECT :segment, :e."airportCodeOrigin",  :e."airportCodeDestination", :e."airlineName", :e."distance", :e."duration" FOREACH e in Edges(:p) WITH ORDINALITY AS segment;
            }
        }
    END
    ;

CALL "TRAVEL"."SP_WeightedTripRouting"('','NTE','PDX',?,?,?,?);
CALL "TRAVEL"."SP_WeightedTripRouting"('distance','NTE','PDX',?,?,?,?);
CALL "TRAVEL"."SP_WeightedTripRouting"('duration','NTE','PDX',?,?,?,?);

---

CREATE TYPE "TRAVEL"."TT_Neighbors" AS TABLE (
    "airportCode" NVARCHAR(3)
    );

CREATE PROCEDURE "TRAVEL"."SP_FindNeighbors" (
        IN airportCode NVARCHAR(3),
        IN direction NVARCHAR(8), -- OUTGOING INCOMING ANY
        IN minDepth INTEGER,
        IN maxDepth INTEGER,
        OUT neighbors "TRAVEL"."TT_Neighbors"
    )
    LANGUAGE GRAPH READS SQL DATA AS
    BEGIN
        Graph g = Graph("TRAVEL", "Flights");
        MULTISET<Vertex> mvNeighbors = NEIGHBORS(:g, [ VERTEX(:g, :airportCode) ], :minDepth, :maxDepth, :direction);
        neighbors = SELECT :v."airportCode" FOREACH v IN :mvNeighbors;
    END
    ;

CALL "TRAVEL"."SP_FindNeighbors"('NTE','OUTGOING',1,1,?);
CALL "TRAVEL"."SP_FindNeighbors"('DFW','INCOMING',1,1,?);

---

CREATE PROCEDURE "TRAVEL"."AirportDestinations" (
        IN airportCode NVARCHAR(3),
        OUT direct INTEGER,
        OUT oneTransfer INTEGER,
        OUT twoTransfers INTEGER
    )
    LANGUAGE GRAPH READS SQL DATA AS
    BEGIN
        Graph g = Graph("TRAVEL", "Flights");
        direct = 0;
        oneTransfer = 0;
        twoTransfers = 0;
        TRAVERSE BFS :g 
            FROM { 
                Vertex(:g, :airportCode)
            } 
            ON VISIT VERTEX (Vertex v, BigInt lvl) {
                IF (:lvl == 1L) {
                    direct = :direct + 1;
                    }
                ELSE {
                    IF (:lvl == 2L) {
                        oneTransfer = :oneTransfer + 1;
                    }
                    ELSE {
                        IF (:lvl == 3L) {
                            twoTransfers = :twoTransfers + 1;
                        }
                    }
                }
            }
        ;
    END
    ;

CALL "TRAVEL"."AirportDestinations"('ATL',?,?,?);
CALL "TRAVEL"."AirportDestinations"('PDX',?,?,?);
CALL "TRAVEL"."AirportDestinations"('YVR',?,?,?);

---

SELECT DISTINCT *
    FROM OPENCYPHER_TABLE (
         GRAPH WORKSPACE "TRAVEL"."Flights"
         QUERY '
            MATCH   (a)-[e]->(b)
            WHERE   a.country = ''United States'' AND 
                    e.distance > 4000 AND 
                    b.altitude < 50 AND
                    e.airlineName ENDS WITH ''lines''
            RETURN  a.airportCode AS airportCodeFrom, 
                    b.airportCode AS airportCodeTo,
                    e.airlineName AS airlineName
         '
    )
    ORDER BY "airportCodeFrom"
    ;

---

SELECT DISTINCT *
    FROM OPENCYPHER_TABLE (
         GRAPH WORKSPACE "TRAVEL"."Flights"
         QUERY '
            MATCH   (a)-[e1]->(b)
            MATCH   (b)-[e2]->(c)
            MATCH   (c)-[e3]->(d)
            WHERE   a.airportCode = ''NTE'' AND
                    d.airportCode = ''PDX'' AND
                    (e1.allianceName = e2.allianceName AND e2.allianceName = e3.allianceName)
            RETURN e1.allianceName AS allianceName,
                    e1.airlineName AS airlineName1,
                    b.airportCode AS transferAirportCode1,
                    e2.airlineName AS airlineName2,
                    c.airportCode AS transferAirportCode2,
                    e3.airlineName AS airlineName3
         '
    )
    ORDER BY "allianceName"
    ;
